---
- block:

  - name: RedHat/CentOS/Fedora | Add Wazuh-Indexer repo
   ## 732 wazuh repo should be added instead.
    yum_repository:
      file: wazuh
      name: wazuh_repo
      description: Wazuh yum repository
      baseurl: "{{ package_repos.yum.indexer.baseurl }}"
      gpgkey: "{{ package_repos.yum.indexer.gpg }}"
      gpgcheck: true
    changed_when: false

#  - name: RedHat/CentOS/Fedora | Install OpenJDK 11
#  ## 732 will not be needed
#    yum:
#      name: java-11-openjdk-devel
#      state: present
#    when:
#      - ansible_distribution != 'Amazon'

#  - name: Amazon Linux | Install OpenJDK 11
#  ## 732 will not be needed
#    block:
#      - name: Install Amazon extras
#        yum:
#          name: amazon-linux-extras
#          state: present

#      - name: Install OpenJDK 11
#        shell: amazon-linux-extras install java-openjdk11 -y

#    when:
#      - ansible_distribution == 'Amazon'

  - name: RedHat/CentOS/Fedora | Install OpenDistro dependencies
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - wget
      - unzip

  - name: Install Wazuh-Indexer
  ## 732 the package name should be updated
    package:
      name: wazuh-indexer-{{ indexer_version }}
      state: present
    register: install
    tags: install

  tags:
  - install
