---
# Cluster Settings
opendistro_version: 4.3.0

single_node: false
elasticsearch_node_name: node-1
opendistro_cluster_name: wazuh
elasticsearch_network_host: '0.0.0.0'

elasticsearch_node_master: true
elasticsearch_node_data: true
elasticsearch_node_ingest: true
elasticsearch_start_timeout: 90

elasticsearch_lower_disk_requirements: false
elasticsearch_cluster_nodes:
  - 127.0.0.1
elasticsearch_discovery_nodes:
  - 127.0.0.1

local_certs_path: "{{ playbook_dir }}/opendistro/certificates"
##check if it is the correct directory

# Minimum master nodes in cluster, 2 for 3 nodes elasticsearch cluster
minimum_master_nodes: 2

# Configure hostnames for Elasticsearch nodes
# Example es1.example.com, es2.example.com
domain_name: wazuh.com

# The OpenDistro package repository
package_repos:
  yum:
    opendistro:
      #baseurl: 'https://packages.wazuh.com/4.x/yum/'
      baseurl: 'https://packages-dev.wazuh.com/pre-release/yum/'
      #gpg: 'https://packages.wazuh.com/key/GPG-KEY-WAZUH'
      gpg: 'https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH'
  apt:
    opendistro:
      #baseurl: 'deb https://packages.wazuh.com/4.x/apt/ stable main'
      baseurl: 'deb https://packages-dev.wazuh.com/pre-release/apt/ unstable main'
      #gpg: 'https://packages.wazuh.com/key/GPG-KEY-WAZUH'
      gpg: 'https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH'
    openjdk:
      baseurl: 'deb http://deb.debian.org/debian stretch-backports main'
      
opendistro_sec_plugin_conf_path: /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig
opendistro_sec_plugin_tools_path: /usr/share/wazuh-indexer/plugins/opensearch-security/tools
opendistro_conf_path: /etc/wazuh-indexer/
opendistro_index_path: /var/lib/wazuh-indexer/

# Security password
opendistro_custom_user: ""
opendistro_custom_user_role: "admin"

# Set JVM memory limits
opendistro_jvm_xms: null

opendistro_http_port: 9700
## 732 this port changes to 9700

certs_gen_tool_version: 4.3
## 732 will no longer be needed. /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-cert-tool.sh comes with the package.

# Url of Search Guard certificates generator tool
certs_gen_tool_url: "https://packages-dev.wazuh.com/resources/{{ certs_gen_tool_version }}/install_functions/opendistro/wazuh-cert-tool.sh"
## 732 will no longer be needed. /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-cert-tool.sh comes with the package.

opendistro_admin_password: changeme
opendistro_kibana_password: changeme

# Deployment settings
generate_certs: true
perform_installation: true

opendistro_nolog_sensible: true
